name: MatrixTestAndBuild

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  workflow_dispatch:
    inputs:
      skip_build:
        description: "Skip the build step"
        required: false
        default: "false"
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: MatrixTestAndBuild
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - name: Run tests
        run: |
          mkdir -p results
          npm test -- --json --outputFile=results/out-${{ matrix.node }}.json
          jq '.numTotalTests' results/out-${{ matrix.node }}.json > results/count-${{ matrix.node }}.txt
      - uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.node }}
          path: results/

  build:
    runs-on: ubuntu-latest
    needs: test
    if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')) && github.event.inputs.skip_build != 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Download results
        uses: actions/download-artifact@v4
        with:
          path: results/
      - name: Merge results
        run: |
          find results -name "out-*.json" -exec cat {} \; | jq -s '.' > summary.json
          find results -name "count-*.txt" -exec cat {} \; > counts.txt
      - name: Check totals
        run: |
          TOTAL=$(awk '{s+=$1} END {print s}' counts.txt)
          echo "Total: $TOTAL"
          if [ -f last.txt ]; then
            LAST=$(cat last.txt)
            if [ "$TOTAL" -lt "$LAST" ]; then
              echo "Decreased from $LAST to $TOTAL"
              exit 1
            fi
          fi
          echo $TOTAL > last.txt
      - name: Save summary
        uses: actions/upload-artifact@v4
        with:
          name: summary
          path: |
            summary.json
            last.txt
      - name: Build
        run: npm run build --if-present
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
