name: Matrix Test & Conditional Build

on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:
    inputs:
      skip_build:
        description: "Skip the build step"
        required: false
        default: "false"
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: npm install

      - name: Create test results directory
        run: mkdir -p test-results

      - name: Run tests
        run: npm test -- --json --outputFile=test-results/results-${{ matrix.node }}.json

      - name: Count tests
        run: jq '.numTotalTests' test-results/results-${{ matrix.node }}.json > test-count-${{ matrix.node }}.txt

      - uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.node }}
          path: |
            test-results/results-${{ matrix.node }}.json
            test-count-${{ matrix.node }}.txt

  build:
    runs-on: ubuntu-latest
    needs: test
    if: (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')) && github.event.inputs.skip_build != 'true'
    environment: release
    steps:
      - uses: actions/checkout@v4

      - name: Download all test results
        uses: actions/download-artifact@v4
        with:
          path: test-results/

      - name: Concatenate test results
        run: |
          jq -s '.' test-results/**/results-*.json > test-results-summary.json
          cat test-results/**/test-count-*.txt > all-test-counts.txt

      - name: Compare test counts
        run: |
          TOTAL=$(awk '{s+=$1} END {print s}' all-test-counts.txt)
          echo "Total tests: $TOTAL"
          if [ -f last-total-tests.txt ]; then
            LAST=$(cat last-total-tests.txt)
            if [ "$TOTAL" -lt "$LAST" ]; then
              echo "Test count decreased from $LAST to $TOTAL"
              exit 1
            fi
          fi
          echo $TOTAL > last-total-tests.txt

      - name: Save test summary
        uses: actions/upload-artifact@v4
        with:
          name: test-summary
          path: |
            test-results-summary.json
            last-total-tests.txt

      - name: Build
        run: npm run build --if-present

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: dist/
