name: Assignment 2 - Matrix Testing & Conditional Build

on:
  push:
    branches:
      - '**'         # run on all branches
    tags:
      - 'v*.*.*'     # run on version tags like v1.0.0
  pull_request:

# ✅ Cancel superseded runs (optional feature)
concurrency:
  group: matrix-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ------------------------------
  # Matrix Test Job
  # ------------------------------
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Save test results
        run: |
          mkdir -p test-results
          echo "✅ Tests passed on Node.js ${{ matrix.node-version }}" > test-results/results-${{ matrix.node-version }}.txt

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results-node-${{ matrix.node-version }}
          path: test-results/

  # ------------------------------
  # Build Job
  # ------------------------------
  build:
    runs-on: ubuntu-latest
    needs: test
    # ✅ Only run build if push is to main OR tag starts with v
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    environment:
      name: release   # ✅ enables optional manual approval if configured in repo Settings > Environments
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-dist
          path: dist/

      - name: Notify
        run: echo "✅ Build completed successfully!"
